name: ai_messenger
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  uuid: ^4.5.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/